name: CI Mac OS X 10.15

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        brew install openslide libomp

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}\
            -DFAST_MODULE_OpenVINO=OFF \
            -DFAST_MODULE_Dicom=OFF \
            -DFAST_MODULE_WholeSlideImaging=ON \
            -DFAST_MODULE_OpenIGTLink=OFF \
            -DFAST_MODULE_Clarius=OFF \
            -DFAST_MODULE_TensorFlow=OFF \
            -DFAST_MODULE_HDF5=OFF \
            -DFAST_MODULE_Plotting=OFF \
            -DFAST_MODULE_Python=OFF \
            -DFAST_MODULE_RealSense=OFF \
            -DFAST_BUILD_EXAMPLES=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    - name: Package
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package -j 4

    - name: Upload archive package
      uses: actions/upload-artifact@v2
      with:
        name: Archive package (tar.xz)
        path: ${{github.workspace}}/build/fast_*.tar.xz
        if-no-files-found: error
